# Generated by Django 3.0.8 on 2020-07-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Book')),
                ('authors', models.ManyToManyField(related_name='books', to='dummy.ForTesting')),
            ],
        ),
    ]
