# Generated by Django 3.0.8 on 2020-07-10 18:11

from django.db import migrations
from dummy.models import ForTesting

def dummy_creator(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    for count in range(10):
        ForTesting.objects.create(
            name=f"Name auto {str(count+1)}",
            description=f"Description auto {str(count+1)}",
        )


class Migration(migrations.Migration):

    dependencies = [
        ('dummy', '0002_book'),
    ]

    operations = [
        migrations.RunPython(dummy_creator),
    ]
